name: freeresc_product_analytics
version: 0.1
display_name: 'Bookatrip: FreeResc Product Analytics'
description: Apps, Flows and actions related to the adoption & revenue KPIs of FreeResc
  product
state: draft
